### PR TITLE
Fix/administration field

### PR DESCRIPTION
**Pull request by jonatanhanson**
rewrote Form component

### CODE REVIEW

**Review by zilaei — COMMENTED** [review]
Check boxes for "Vilka får låna" not unchecked:
1) Selecting "Flera" from drop down and checking few options
2) Regretting and selecting "Alla" from drop down.
3) Check boxes from step 1 are still enabled and stored in DB when ad created

**Comment by jonatanhanson** [comment]
> 



> This might be outside of scope for what I should test in this PR, disregard in that case.
> 
> Check boxes for "Vilka får låna" not unchecked:
> 
>     1. Selecting "Flera" from drop down and checking few options
> 
>     2. Regretting and selecting "Alla" from drop down.
> 
>     3. Check boxes from step 1 are still enabled and stored in DB when ad created.

I know what you mean and that problem goes for all conditional fields. So we might need add functionality to "reset" the field to it's default value when hidden. 

But i don't think it will be a problem right now because we must check the selected value first before doing any restriction. So if the select has value "Alla", we dont use the list with "Förvatlningar" at all, even if it has values.

**Comment by zilaei** [comment]
> > 
> 
> > This might be outside of scope for what I should test in this PR, disregard in that case.
> > Check boxes for "Vilka får låna" not unchecked:
> > ```
> > 1. Selecting "Flera" from drop down and checking few options
> > 
> > 2. Regretting and selecting "Alla" from drop down.
> > 
> > 3. Check boxes from step 1 are still enabled and stored in DB when ad created.
> > ```
> 
> I know what you mean and that problem goes for all conditional fields. So we might need add functionality to "reset" the field to it's default value when hidden.
> 
> But i don't think it will be a problem right now because we must check the selected value first before doing any restriction. So if the select has value "Alla", we dont use the list with "Förvatlningar" at all, even if it has values.

OK.
Anything in particular you would like me to look at? 
Form still needs some work, it's still messy but you probably know that.

**Comment by jonatanhanson** [comment]
> > > 
> > 
> > 
> > > This might be outside of scope for what I should test in this PR, disregard in that case.
> > > Check boxes for "Vilka får låna" not unchecked:
> > > ```
> > > 1. Selecting "Flera" from drop down and checking few options
> > > 
> > > 2. Regretting and selecting "Alla" from drop down.
> > > 
> > > 3. Check boxes from step 1 are still enabled and stored in DB when ad created.
> > > ```
> > 
> > 
> > I know what you mean and that problem goes for all conditional fields. So we might need add functionality to "reset" the field to it's default value when hidden.
> > But i don't think it will be a problem right now because we must check the selected value first before doing any restriction. So if the select has value "Alla", we dont use the list with "Förvatlningar" at all, even if it has values.
> 
> OK. Anything in particular you would like me to look at? Form still needs some work, it's still messy but you probably know that.

i think we can look into it if it will be a problem later on.
Yep the whole component is still too large but it's less hardcoded and better stuctured atleast ;P

**Pull request closed without merging**
