### PR TITLE
Fix/google maps

### PR DESCRIPTION
**Pull request by rubikuo**
### **Explain the changes you've made**
Fixed the map bug.
Put the map into Item detail page according to design

### **Explain why these changes are made**
There was a bug and the design in item detail page has been updated.

### **Explain your solution**
use the state of the scriptisloaded to fixed the bug.
Adjust in CSS

### **How to test the changes?**

go to item detail page, check if the map is buggy and if the design are all in place

### CODE REVIEW

**Review by annaeklov — CHANGES_REQUESTED** [review]
image
Description text must align with design.

**Review by annaeklov — CHANGES_REQUESTED** [review]
image
remove min-width and it might work. because now the map is too big

**Review by annaeklov — CHANGES_REQUESTED** [review]
it only shows the map the first time i'm clicking into details, and never more. I need to refresh the page to get it to work again.

**Review by JohannaENilsson — APPROVED** [review]
Looks great. Good job :)

**Pull request merged**
